"""ros0411_products_hardening

Revision ID: 32c6534227ef
Revises: 
Create Date: 2026-07-16 09:31:25.717830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c6534227ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('modifier_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('selection_type', sa.Enum('SINGLE', 'MULTIPLE', name='modifier_selection_type_enum'), nullable=False),
    sa.Column('minimum_required', sa.Integer(), nullable=False),
    sa.Column('maximum_allowed', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_modifier_groups_product_name')
    )
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modifier_groups_product_id'), ['product_id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_product_prices_amount_positive'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_product_prices_effective_window'),
    sa.CheckConstraint('length(currency) = 3', name='ck_product_prices_currency_len'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index('ix_product_prices_active_unique', ['product_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
        batch_op.create_index(batch_op.f('ix_product_prices_product_id'), ['product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_variants_product_name')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=True)

    op.create_table('modifier_options',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('modifier_group_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modifier_group_id', 'name', name='uq_modifier_options_group_name')
    )
    with op.batch_alter_table('modifier_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modifier_options_modifier_group_id'), ['modifier_group_id'], unique=False)

    op.create_table('variant_prices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('variant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_variant_prices_amount_positive'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_variant_prices_effective_window'),
    sa.CheckConstraint('length(currency) = 3', name='ck_variant_prices_currency_len'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variant_prices', schema=None) as batch_op:
        batch_op.create_index('ix_variant_prices_active_unique', ['variant_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
        batch_op.create_index(batch_op.f('ix_variant_prices_variant_id'), ['variant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variant_prices_variant_id'))
        batch_op.drop_index('ix_variant_prices_active_unique', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    op.drop_table('variant_prices')
    with op.batch_alter_table('modifier_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modifier_options_modifier_group_id'))

    op.drop_table('modifier_options')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_product_id'))
        batch_op.drop_index('ix_product_prices_active_unique', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    op.drop_table('product_prices')
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modifier_groups_product_id'))

    op.drop_table('modifier_groups')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))

    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('product_categories')
    op.drop_table('permissions')
    # ### end Alembic commands ###
